version: '3'

services:
  db:
    image: mariadb:latest
    restart: unless-stopped
    volumes:
      - qrman_db:/var/lib/mysql
      #- /var/lib/docker/volumes/qrenv/_data/.env:.env
    environment:
      ADMIN_NAME: Alessandro
      ADMIN_SURNAME: Caviglione
      ADMIN_EMAIL: ac@prisma-group.ch
      ADMIN_PASSWORD: Capoitaly80!
      MYSQL_ROOT_PASSWORD: changeme
      MYSQL_PASSWORD: changeme
      MYSQL_DATABASE: semioqr
      MYSQL_HOST: db
      MARIADB_AUTO_UPGRADE: 1
      MARIADB_DISABLE_UPGRADE_BACKUP: 1
      BROADCAST_DRIVER: log
      #CACHE_DRIVER: redis
      QUEUE_CONNECTION: sync
      SESSION_DRIVER: file
      SESSION_LIFETIME: 120
      REDIS_HOST: qr_redis
      REDIS_PASSWORD: null
      REDIS_PORT: 6379
      FIRST_RUN: 0
    networks:
      - qrcode-network
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.hostname == itmidkw01

  redis:
    image: redis:alpine
    networks:
      - qrcode-network
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.hostname == itmidkw01

  app:
    image: ghcr.io/semiodigital/qrman:latest
    volumes:
      - qrman_config:/app/config
      - /var/lib/docker/volumes/qrenv/_data/.env:/app/.env.sys
      - /var/lib/docker/volumes/qrenv/_data/.env.laravel:/app/.env
      - qrman_storage:/app/storage
    env_file:
      - .env
    networks:
      - proxy
      - qrcode-network
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.hostname == itmidkw01
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - "8091:80"
    environment:
      PMA_HOST: qr_db
      MYSQL_ROOT_PASSWORD: changeme
    networks:
      - qrcode-network

networks:
  qrcode-network:
    driver: overlay
  proxy:
    external: true

volumes:
 qrman_db:
  driver: local
  driver_opts:
      type: "nfs"
      o: "addr=172.16.100.103,rw,bg,hard,vers=4,proto=tcp,timeo=600,rsize=65536,wsize=65536,nointr"
      device: ":/DOCKER/qrman/db"
 qrman_config:
  driver: local
  driver_opts:
      type: "nfs"
      o: "addr=172.16.100.103,rw,bg,hard,vers=4,proto=tcp,timeo=600,rsize=65536,wsize=65536,nointr"
      device: ":/DOCKER/qrman/config"
 qrman_storage:
  driver: local
  driver_opts:
      type: "nfs"
      o: "addr=172.16.100.103,rw,bg,hard,vers=4,proto=tcp,timeo=600,rsize=65536,wsize=65536,nointr"
      device: ":/DOCKER/qrman/storage"
